[package]
name = "scrypt-wasm"
version = "0.1.1"
authors = ["Kosala Hemachandra <kvhnuke@aol.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
rust-crypto-wasm = "^0.3"
hex = "^0.3"